name: Conformance tests
on:
  pull_request:
    branches:
      - 'main'
      - 'release*'

jobs:
  run-conformace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # pin@v3
        with:
          go-version: ~1.18.6
      - name: Kyverno conformance tests
        run: go run ./test/conformance/main.go
