name: Conformance tests
on:
  pull_request:
    branches:
      - 'main'
      - 'release*'

jobs:
  run-conformace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Setup go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
        with:
          go-version: ~1.18.6
      - name: Kyverno conformance tests
        run: go run ./test/conformance/main.go
